// src/components/PptWorkspace.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import { GenerationTimeline } from "./GenerationTimeline";
import { SlidePreview } from "./SlidePreview";
import { TemplatePicker } from "./TemplatePicker";
import type {
  PptJobEvent,
  PptFillAnimation,
  PptJobStatus,
  PptStepKey,
  PptTemplate,
  RenderedSlide,
} from "@/lib/ppt/types";

type WorkspaceStatus = PptJobStatus | "idle";

interface TemplatesResponse {
  templates?: PptTemplate[];
  error?: string;
}

interface CreateJobResponse {
  jobId?: string;
  error?: string;
}

const terminalStatuses: WorkspaceStatus[] = ["completed", "failed"];
const maxEventSourceRetries = 3;
const eventSourceRetryDelayMs = 700;

export function PptWorkspace() {
  const [topic, setTopic] = useState("");
  const [templates, setTemplates] = useState<PptTemplate[]>([]);
  const [selectedTemplateId, setSelectedTemplateId] = useState<string>();
  const [jobId, setJobId] = useState<string>();
  const [status, setStatus] = useState<WorkspaceStatus>("idle");
  const [currentStep, setCurrentStep] = useState<PptStepKey>("analyzing");
  const [progress, setProgress] = useState(0);
  const [slides, setSlides] = useState<RenderedSlide[]>([]);
  const [activeSlideIndex, setActiveSlideIndex] = useState(0);
  const [animation, setAnimation] = useState<PptFillAnimation>();
  const [currentMessage, setCurrentMessage] = useState("等待开始生成");
  const [error, setError] = useState<string>();
  const terminalRef = useRef(false);
  const isSubmittingRef = useRef(false);

  const selectedTemplate = templates.find(
    (template) => template.id === selectedTemplateId,
  );
  const activeSlide = slides[activeSlideIndex] ?? slides[0];
  const isGenerating = status === "queued" || status === "running";
  const canGenerate =
    topic.trim().length > 0 && Boolean(selectedTemplateId) && !isGenerating;

  useEffect(() => {
    let cancelled = false;

    async function loadTemplates() {
      try {
        const response = await fetch("/api/templates");
        const data = (await response.json()) as TemplatesResponse;

        if (!response.ok) {
          throw new Error(data.error ?? "模板加载失败。");
        }

        if (!cancelled) {
          const nextTemplates = data.templates ?? [];
          setTemplates(nextTemplates);
          setSelectedTemplateId((currentId) => currentId ?? nextTemplates[0]?.id);
        }
      } catch (loadError) {
        if (!cancelled) {
          setError(
            loadError instanceof Error ? loadError.message : "模板加载失败。",
          );
        }
      }
    }

    void loadTemplates();

    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    if (!jobId) return undefined;

    terminalRef.current = false;
    let disposed = false;
    let retryCount = 0;
    let retryTimer: ReturnType<typeof setTimeout> | undefined;
    let eventSource: EventSource | undefined;

    const closeEventSource = () => {
      eventSource?.close();
      eventSource = undefined;
    };

    const openEventSource = () => {
      closeEventSource();
      eventSource = new EventSource(`/api/ppt/jobs/${jobId}/events`);

      eventSource.onmessage = (message) => {
        try {
          const event = JSON.parse(message.data) as PptJobEvent;
          retryCount = 0;

          setStatus(event.status);
          setCurrentStep(event.step);
          setProgress(event.progress);
          setError(event.error);
          setAnimation(event.animation);
          setCurrentMessage(event.message);

          if (event.slides) {
            setSlides(event.slides);
            setActiveSlideIndex((currentIndex) =>
              event.animation
                ? event.animation.slideIndex
                : event.slides && currentIndex < event.slides.length ? currentIndex : 0,
            );
          }

          if (terminalStatuses.includes(event.status)) {
            terminalRef.current = true;
            closeEventSource();
          }
        } catch {
          setError("生成事件解析失败，请重新生成。");
          setStatus("failed");
          terminalRef.current = true;
          closeEventSource();
        }
      };

      eventSource.onerror = () => {
        if (disposed || terminalRef.current) return;
        closeEventSource();

        if (retryCount < maxEventSourceRetries) {
          retryCount += 1;
          retryTimer = setTimeout(openEventSource, eventSourceRetryDelayMs);
          return;
        }

        setError("生成进度连接中断，请重新生成。");
        setStatus("failed");
        terminalRef.current = true;
      };
    };

    openEventSource();

    return () => {
      disposed = true;
      if (retryTimer) {
        clearTimeout(retryTimer);
      }
      closeEventSource();
    };
  }, [jobId]);

  useEffect(() => {
    if (terminalStatuses.includes(status)) {
      isSubmittingRef.current = false;
    }
  }, [status]);

  const handleGenerate = async () => {
    if (!selectedTemplateId || !canGenerate || isSubmittingRef.current) return;

    isSubmittingRef.current = true;
    setError(undefined);
    setSlides([]);
    setActiveSlideIndex(0);
    setProgress(0);
    setCurrentStep("analyzing");
    setAnimation(undefined);
    setCurrentMessage("正在创建生成任务");
    setStatus("queued");
    setJobId(undefined);
    terminalRef.current = false;

    try {
      const response = await fetch("/api/ppt/jobs", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          topic: topic.trim(),
          templateId: selectedTemplateId,
        }),
      });
      const data = (await response.json()) as CreateJobResponse;

      if (!response.ok || !data.jobId) {
        throw new Error(data.error ?? "创建生成任务失败。");
      }

      setJobId(data.jobId);
    } catch (createError) {
      setStatus("failed");
      isSubmittingRef.current = false;
      setError(
        createError instanceof Error ? createError.message : "创建生成任务失败。",
      );
    }
  };

  return (
    <main className="workspace-shell">
      <section className="workspace-panel workspace-panel--input">
        <div className="panel-heading">
          <span className="eyebrow">AI PPT Generator</span>
          <h1>把主题生成可下载 PPT</h1>
        </div>

        <label className="topic-field" htmlFor="ppt-topic">
          <span>汇报主题</span>
          <textarea
            id="ppt-topic"
            onChange={(event) => setTopic(event.target.value)}
            placeholder="例如：2026 年新能源车市场增长策略"
            rows={6}
            value={topic}
          />
        </label>

        <div className="control-group">
          <div className="control-group__header">
            <span>模板</span>
            {selectedTemplate ? <em>{selectedTemplate.theme}</em> : null}
          </div>
          <TemplatePicker
            onSelect={setSelectedTemplateId}
            selectedTemplateId={selectedTemplateId}
            templates={templates}
          />
        </div>

        {error ? (
          <div className="error-banner" role="alert">
            {error}
          </div>
        ) : null}

        <div className="action-row">
          <button
            className="primary-action"
            disabled={!canGenerate}
            onClick={handleGenerate}
            type="button"
          >
            {isGenerating ? "生成中..." : status === "failed" ? "重新生成" : "生成 PPT"}
          </button>
          {status === "completed" && jobId ? (
            <a
              className="download-action"
              href={`/api/ppt/jobs/${jobId}/download`}
            >
              下载 PPTX
            </a>
          ) : null}
        </div>

        <GenerationTimeline
          currentStep={currentStep}
          progress={progress}
          status={status}
        />
      </section>

      <section className="workspace-panel workspace-panel--slides">
        <div className="preview-toolbar">
          <div>
            <span className="eyebrow">预览</span>
            <h2>{slides.length > 0 ? `${slides.length} 页幻灯片` : "等待生成"}</h2>
            <p>{currentMessage}</p>
          </div>
          <span className={`status-pill status-pill--${status}`}>{status}</span>
        </div>

        <div className="preview-stage">
          {activeSlide ? (
            <SlidePreview
              active
              animation={animation?.slideIndex === activeSlide.index ? animation : undefined}
              mode="large"
              slide={activeSlide}
            />
          ) : (
            <div className="empty-preview">
              <span>16:9</span>
              <strong>生成后在这里查看完整页面</strong>
            </div>
          )}
        </div>

        {slides.length > 0 ? (
          <div className="slide-strip" aria-label="幻灯片缩略图">
            {slides.map((slide, index) => (
              <div className="slide-strip__item" key={slide.id}>
                <span>{String(index + 1).padStart(2, "0")}</span>
                <SlidePreview
                  active={index === activeSlideIndex}
                  mode="thumbnail"
                  onSelect={() => setActiveSlideIndex(index)}
                  slide={slide}
                />
              </div>
            ))}
          </div>
        ) : null}
      </section>
    </main>
  );
}

// src/frontend/components/PptWorkspace.vue
<template>
  <main class="workspace-shell">
    <aside class="control-rail">
      <div class="brand-block">
        <span class="eyebrow">YiCe AI PPT</span>
        <h1>动态生成演示文稿</h1>
      </div>

      <label class="topic-field" for="ppt-topic">
        <span>汇报主题</span>
        <textarea
          id="ppt-topic"
          v-model="topic"
          placeholder="例如：2026 年新能源车市场增长策略"
          rows="7"
        />
      </label>

      <section class="control-group" aria-label="模板">
        <div class="control-group__header">
          <span>模板风格</span>
          <em v-if="selectedTemplate">{{ selectedTemplate.theme }}</em>
        </div>
        <TemplatePicker
          :selected-template-id="selectedTemplateId"
          :templates="templates"
          @select="selectedTemplateId = $event"
        />
      </section>

      <div v-if="error" class="error-banner" role="alert">
        {{ error }}
      </div>

      <div class="action-row">
        <button
          class="primary-action"
          :disabled="!canGenerate"
          type="button"
          @click="handleGenerate"
        >
          {{ generateLabel }}
        </button>
        <a
          v-if="status === 'completed' && jobId"
          class="download-action"
          :href="`/api/ppt/jobs/${jobId}/download`"
        >
          下载 PPTX
        </a>
      </div>

      <GenerationTimeline
        :current-step="currentStep"
        :progress="progress"
        :status="status"
      />
    </aside>

    <section class="preview-workbench" aria-label="幻灯片动态预览">
      <header class="preview-toolbar">
        <div>
          <span class="eyebrow">实时预览</span>
          <h2>{{ slides.length > 0 ? `${slides.length} 页幻灯片` : "等待生成" }}</h2>
          <p>{{ currentMessage }}</p>
        </div>
        <span :class="['status-pill', `status-pill--${status}`]">{{ status }}</span>
      </header>

      <div class="preview-stage">
        <SlidePreview
          v-if="activeSlide"
          active
          :animation="activeSlideAnimation"
          mode="large"
          :slide="activeSlide"
        />
        <div v-else class="empty-preview">
          <span>16:9</span>
          <strong>生成后在这里查看完整页面</strong>
        </div>
      </div>

      <div v-if="slides.length > 0" class="slide-strip" aria-label="幻灯片缩略图">
        <div v-for="(slide, index) in slides" :key="slide.id" class="slide-strip__item">
          <span>{{ String(index + 1).padStart(2, "0") }}</span>
          <SlidePreview
            :active="index === activeSlideIndex"
            mode="thumbnail"
            selectable
            :slide="slide"
            @select="activeSlideIndex = index"
          />
        </div>
      </div>
    </section>
  </main>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import GenerationTimeline from "./GenerationTimeline.vue";
import SlidePreview from "./SlidePreview.vue";
import TemplatePicker from "./TemplatePicker.vue";
import type {
  CreateJobResponse,
  PptFillAnimation,
  PptJobEvent,
  PptStepKey,
  PptTemplate,
  RenderedSlide,
  TemplatesResponse,
  WorkspaceStatus,
} from "@/frontend/types/ppt";

const terminalStatuses: WorkspaceStatus[] = ["completed", "failed"];
const maxEventSourceRetries = 3;
const eventSourceRetryDelayMs = 700;

const topic = ref("");
const templates = ref<PptTemplate[]>([]);
const selectedTemplateId = ref<string>();
const jobId = ref<string>();
const status = ref<WorkspaceStatus>("idle");
const currentStep = ref<PptStepKey>("analyzing");
const progress = ref(0);
const slides = ref<RenderedSlide[]>([]);
const activeSlideIndex = ref(0);
const animation = ref<PptFillAnimation>();
const currentMessage = ref("等待开始生成");
const error = ref<string>();
const terminal = ref(false);
const isSubmitting = ref(false);
const eventSource = ref<EventSource>();
const retryTimer = ref<ReturnType<typeof setTimeout>>();

let disposed = false;

const selectedTemplate = computed(() =>
  templates.value.find((template) => template.id === selectedTemplateId.value),
);
const activeSlide = computed(
  () => slides.value[activeSlideIndex.value] ?? slides.value[0],
);
const activeSlideAnimation = computed(() =>
  animation.value?.slideIndex === activeSlide.value?.index ? animation.value : undefined,
);
const isGenerating = computed(
  () => status.value === "queued" || status.value === "running",
);
const canGenerate = computed(
  () =>
    topic.value.trim().length > 0 &&
    Boolean(selectedTemplateId.value) &&
    !isGenerating.value,
);
const generateLabel = computed(() => {
  if (isGenerating.value) return "生成中...";
  if (status.value === "failed") return "重新生成";
  return "生成 PPT";
});

const closeEventSource = () => {
  eventSource.value?.close();
  eventSource.value = undefined;
};

const loadTemplates = async () => {
  try {
    const response = await fetch("/api/templates");
    const data = (await response.json()) as TemplatesResponse;

    if (!response.ok) {
      throw new Error(data.error ?? "模板加载失败。");
    }

    const nextTemplates = data.templates ?? [];
    templates.value = nextTemplates;
    selectedTemplateId.value = selectedTemplateId.value ?? nextTemplates[0]?.id;
  } catch (loadError) {
    error.value = loadError instanceof Error ? loadError.message : "模板加载失败。";
  }
};

const openEventSource = (id: string, retryCount = 0) => {
  closeEventSource();
  eventSource.value = new EventSource(`/api/ppt/jobs/${id}/events`);

  eventSource.value.onmessage = (message) => {
    try {
      const event = JSON.parse(message.data) as PptJobEvent;

      status.value = event.status;
      currentStep.value = event.step;
      progress.value = event.progress;
      error.value = event.error;
      animation.value = event.animation;
      currentMessage.value = event.message;

      if (event.slides) {
        slides.value = event.slides;
        activeSlideIndex.value = event.animation
          ? event.animation.slideIndex
          : activeSlideIndex.value < event.slides.length
            ? activeSlideIndex.value
            : 0;
      }

      if (terminalStatuses.includes(event.status)) {
        terminal.value = true;
        closeEventSource();
      }
    } catch {
      error.value = "生成事件解析失败，请重新生成。";
      status.value = "failed";
      terminal.value = true;
      closeEventSource();
    }
  };

  eventSource.value.onerror = () => {
    if (disposed || terminal.value) return;
    closeEventSource();

    if (retryCount < maxEventSourceRetries) {
      retryTimer.value = setTimeout(
        () => openEventSource(id, retryCount + 1),
        eventSourceRetryDelayMs,
      );
      return;
    }

    error.value = "生成进度连接中断，请重新生成。";
    status.value = "failed";
    terminal.value = true;
  };
};

const handleGenerate = async () => {
  if (!selectedTemplateId.value || !canGenerate.value || isSubmitting.value) return;

  isSubmitting.value = true;
  error.value = undefined;
  slides.value = [];
  activeSlideIndex.value = 0;
  progress.value = 0;
  currentStep.value = "analyzing";
  animation.value = undefined;
  currentMessage.value = "正在创建生成任务";
  status.value = "queued";
  jobId.value = undefined;
  terminal.value = false;

  try {
    const response = await fetch("/api/ppt/jobs", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        topic: topic.value.trim(),
        templateId: selectedTemplateId.value,
      }),
    });
    const data = (await response.json()) as CreateJobResponse;

    if (!response.ok || !data.jobId) {
      throw new Error(data.error ?? "创建生成任务失败。");
    }

    jobId.value = data.jobId;
    openEventSource(data.jobId);
  } catch (createError) {
    status.value = "failed";
    isSubmitting.value = false;
    error.value =
      createError instanceof Error ? createError.message : "创建生成任务失败。";
  }
};

watch(status, (nextStatus) => {
  if (terminalStatuses.includes(nextStatus)) {
    isSubmitting.value = false;
  }
});

onMounted(() => {
  void loadTemplates();
});

onBeforeUnmount(() => {
  disposed = true;
  if (retryTimer.value) {
    clearTimeout(retryTimer.value);
  }
  closeEventSource();
});
</script>
