// src/components/SlidePreview.tsx
import React from "react";
import type {
  AccentElement,
  BoxRegion,
  PptFillAnimation,
  RenderedSlide,
} from "@/lib/ppt/types";

export interface SlidePreviewProps {
  slide: RenderedSlide;
  mode?: "thumbnail" | "large";
  active?: boolean;
  animation?: PptFillAnimation;
  onSelect?: () => void;
}

const toRegionStyle = (region: BoxRegion): React.CSSProperties => ({
  left: `${region.x * 100}%`,
  top: `${region.y * 100}%`,
  width: `${region.w * 100}%`,
  height: `${region.h * 100}%`,
});

const toAccentStyle = (accentElement: AccentElement): React.CSSProperties => ({
  ...toRegionStyle(accentElement.region),
  backgroundColor: accentElement.color,
  opacity: accentElement.opacity ?? 1,
});

export function SlidePreview({
  slide,
  mode = "large",
  active = false,
  animation,
  onSelect,
}: SlidePreviewProps) {
  const { colors, fontFamily, layout } = slide.style;
  const liveAnimation = mode === "large" ? animation : undefined;
  const activeField = liveAnimation?.field;
  const activeBulletIndex = liveAnimation?.bulletIndex;
  const generationCue = getGenerationCue(slide.index, liveAnimation);
  const content = (
    <div
      className={`slide-frame slide-frame--${mode} slide-frame--${slide.status}`}
      data-animation-field={activeField}
      style={{
        background: slide.style.background,
        color: colors.text,
        fontFamily,
      }}
    >
      {layout.accentElements.map((accentElement) => (
        <span
          aria-hidden="true"
          className={`slide-accent slide-accent--${accentElement.type}`}
          key={accentElement.id}
          style={toAccentStyle(accentElement)}
        />
      ))}

      <div
        className={`slide-title${activeField === "title" ? " is-filling" : ""}`}
        style={toRegionStyle(layout.titleBox)}
      >
        {slide.title || <span className="slide-placeholder slide-placeholder--title" />}
      </div>

      {layout.subtitleBox ? (
        <div
          className={`slide-subtitle${
            activeField === "subtitle" ? " is-filling" : ""
          }`}
          style={{
            ...toRegionStyle(layout.subtitleBox),
            color: colors.mutedText,
          }}
        >
          {slide.subtitle || <span className="slide-placeholder slide-placeholder--subtitle" />}
        </div>
      ) : null}

      {layout.bodyBox ? (
        slide.bullets.length > 0 ? (
          <ul
            className={`slide-bullets${
              activeField === "bullets" ? " is-filling" : ""
            }`}
            style={toRegionStyle(layout.bodyBox)}
          >
            {slide.bullets.map((bullet, index) => (
              <li
                className={activeBulletIndex === index ? "is-active-bullet" : undefined}
                data-active-bullet={activeBulletIndex === index || undefined}
                key={`${slide.id}-bullet-${index}`}
              >
                {bullet}
              </li>
            ))}
          </ul>
        ) : (
          <div className="slide-bullet-placeholders" style={toRegionStyle(layout.bodyBox)}>
            <span />
            <span />
            <span />
          </div>
        )
      ) : null}

      {generationCue ? (
        <div className="slide-generation-cue" aria-live="polite">
          <span>{String(slide.index + 1).padStart(2, "0")}</span>
          <strong>{generationCue}</strong>
        </div>
      ) : null}
    </div>
  );

  if (!onSelect) {
    return content;
  }

  return (
    <button
      aria-label={`查看第 ${slide.index + 1} 页：${slide.title}`}
      aria-pressed={active}
      className={`slide-thumb-button${active ? " is-active" : ""}`}
      onClick={onSelect}
      type="button"
    >
      {content}
    </button>
  );
}

const getGenerationCue = (
  slideIndex: number,
  animation?: PptFillAnimation,
): string | undefined => {
  if (!animation) return undefined;

  const page = slideIndex + 1;

  if (animation.phase === "template") {
    return "正在铺设 PPT 模板骨架";
  }

  if (animation.field === "title") {
    return `正在填充第 ${page} 页标题`;
  }

  if (animation.field === "subtitle") {
    return `正在填充第 ${page} 页副标题`;
  }

  if (animation.field === "bullets") {
    return `正在填充第 ${page} 页要点 ${(animation.bulletIndex ?? 0) + 1}`;
  }

  if (animation.phase === "ready") {
    return `第 ${page} 页已生成`;
  }

  return undefined;
};

// src/frontend/components/SlidePreview.vue
<template>
  <button
    v-if="selectable"
    :aria-label="`查看第 ${slide.index + 1} 页：${slide.title || '未填充页面'}`"
    :aria-pressed="active"
    :class="['slide-thumb-button', { 'is-active': active }]"
    type="button"
    @click="emit('select')"
  >
    <SlideCanvas />
  </button>
  <SlideCanvas v-else />
</template>

<script setup lang="ts">
import { computed, defineComponent, h } from "vue";
import type {
  AccentElement,
  BoxRegion,
  PptFillAnimation,
  RenderedSlide,
} from "@/frontend/types/ppt";

const props = withDefaults(
  defineProps<{
    slide: RenderedSlide;
    mode?: "thumbnail" | "large";
    active?: boolean;
    animation?: PptFillAnimation;
    selectable?: boolean;
  }>(),
  {
    mode: "large",
    active: false,
    selectable: false,
  },
);

const emit = defineEmits<{
  select: [];
}>();

const liveAnimation = computed(() =>
  props.mode === "large" ? props.animation : undefined,
);
const activeField = computed(() => liveAnimation.value?.field);
const activeBulletIndex = computed(() => liveAnimation.value?.bulletIndex);
const generationCue = computed(() =>
  getGenerationCue(props.slide.index, liveAnimation.value),
);

const toRegionStyle = (region: BoxRegion) => ({
  left: `${region.x * 100}%`,
  top: `${region.y * 100}%`,
  width: `${region.w * 100}%`,
  height: `${region.h * 100}%`,
});

const toAccentStyle = (accentElement: AccentElement) => ({
  ...toRegionStyle(accentElement.region),
  backgroundColor: accentElement.color,
  opacity: accentElement.opacity ?? 1,
});

const SlideCanvas = defineComponent({
  name: "SlideCanvas",
  setup() {
    return () => {
      const { colors, fontFamily, layout } = props.slide.style;

      return h(
        "div",
        {
          class: [
            "slide-frame",
            `slide-frame--${props.mode}`,
            `slide-frame--${props.slide.status}`,
          ],
          "data-animation-field": activeField.value,
          style: {
            background: props.slide.style.background,
            color: colors.text,
            fontFamily,
          },
        },
        [
          ...layout.accentElements.map((accentElement) =>
            h("span", {
              "aria-hidden": "true",
              class: ["slide-accent", `slide-accent--${accentElement.type}`],
              key: accentElement.id,
              style: toAccentStyle(accentElement),
            }),
          ),
          h(
            "div",
            {
              class: ["slide-title", { "is-filling": activeField.value === "title" }],
              style: toRegionStyle(layout.titleBox),
            },
            props.slide.title
              ? props.slide.title
              : h("span", { class: "slide-placeholder slide-placeholder--title" }),
          ),
          layout.subtitleBox
            ? h(
                "div",
                {
                  class: [
                    "slide-subtitle",
                    { "is-filling": activeField.value === "subtitle" },
                  ],
                  style: {
                    ...toRegionStyle(layout.subtitleBox),
                    color: colors.mutedText,
                  },
                },
                props.slide.subtitle
                  ? props.slide.subtitle
                  : h("span", {
                      class: "slide-placeholder slide-placeholder--subtitle",
                    }),
              )
            : undefined,
          layout.bodyBox
            ? props.slide.bullets.length > 0
              ? h(
                  "ul",
                  {
                    class: [
                      "slide-bullets",
                      { "is-filling": activeField.value === "bullets" },
                    ],
                    style: toRegionStyle(layout.bodyBox),
                  },
                  props.slide.bullets.map((bullet, index) =>
                    h(
                      "li",
                      {
                        class: {
                          "is-active-bullet": activeBulletIndex.value === index,
                        },
                        "data-active-bullet":
                          activeBulletIndex.value === index ? "true" : undefined,
                        key: `${props.slide.id}-bullet-${index}`,
                      },
                      bullet,
                    ),
                  ),
                )
              : h(
                  "div",
                  {
                    class: "slide-bullet-placeholders",
                    style: toRegionStyle(layout.bodyBox),
                  },
                  [h("span"), h("span"), h("span")],
                )
            : undefined,
          generationCue.value
            ? h(
                "div",
                { class: "slide-generation-cue", "aria-live": "polite" },
                [
                  h("span", String(props.slide.index + 1).padStart(2, "0")),
                  h("strong", generationCue.value),
                ],
              )
            : undefined,
        ],
      );
    };
  },
});

const getGenerationCue = (
  slideIndex: number,
  animation?: PptFillAnimation,
): string | undefined => {
  if (!animation) return undefined;

  const page = slideIndex + 1;

  if (animation.phase === "template") {
    return "正在铺设 PPT 模板骨架";
  }

  if (animation.field === "title") {
    return `正在填充第 ${page} 页标题`;
  }

  if (animation.field === "subtitle") {
    return `正在填充第 ${page} 页副标题`;
  }

  if (animation.field === "bullets") {
    return `正在填充第 ${page} 页要点 ${(animation.bulletIndex ?? 0) + 1}`;
  }

  if (animation.phase === "ready") {
    return `第 ${page} 页已生成`;
  }

  return undefined;
};
</script>
